linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - lll
    - noctx
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - goprintffuncname
    - nolintlint
    - dupl
    - gochecknoinits

 # don't enable:
 #  - golint        # deprecated
 #  - whitespace
 #  - funlen
 #  - exhaustive
 #  - gomnd
 #  - gofmt

run:
  deadline: 3m
linters-settings:
  lll:
    line-length: 150

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: main.go
      linters:
        - gochecknoinits
    - path: gslb_types.go
      linters:
        - gochecknoinits
