package controllers

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"testing"

	"github.com/k8gb-io/k8gb/controllers/depresolver"
	"github.com/stretchr/testify/require"
)

func TestChangeAnnotationValue(t *testing.T) {
	const key = "field.cattle.io/publicEndpoints"
	settings := provideSettings(t, predefinedConfig)
	settings.ingress.Annotations[key] = "1.1.1.1"
	_ = settings.client.Update(context.TODO(), settings.ingress)
	settings.reconciler.createGSLBFromIngress(settings.client, settings.ingress, strategyAnnotation, depresolver.RoundRobinStrategy)
	_ = settings.reconciler.Get(context.TODO(), settings.request.NamespacedName, settings.gslb)
	require.Equal(t, len(settings.gslb.Annotations), 2)
	require.Equal(t, settings.gslb.Annotations[key], "1.1.1.1")

	settings.ingress.Annotations[key] = "1.1.1.2"
	_ = settings.client.Update(context.Background(), settings.ingress)
	settings.reconciler.createGSLBFromIngress(settings.client, settings.ingress, strategyAnnotation, depresolver.RoundRobinStrategy)
	_ = settings.reconciler.Get(context.TODO(), settings.request.NamespacedName, settings.gslb)
	require.Equal(t, len(settings.gslb.Annotations), 2)
	require.Equal(t, settings.gslb.Annotations[key], "1.1.1.2")
}

func TestChangeAnnotationValueWithReconcile(t *testing.T) {
	const key = "field.cattle.io/publicEndpoints"
	settings := provideSettings(t, predefinedConfig)
	settings.ingress.Annotations[key] = "1.1.1.1"
	_ = settings.client.Update(context.TODO(), settings.ingress)
	settings.reconciler.createGSLBFromIngress(settings.client, settings.ingress, strategyAnnotation, depresolver.RoundRobinStrategy)
	reconcileAndUpdateGslb(t, settings)
	require.Equal(t, len(settings.gslb.Annotations), 2)
	require.Equal(t, settings.gslb.Annotations[key], "1.1.1.1")

	settings.ingress.Annotations[key] = "1.1.1.2"
	_ = settings.client.Update(context.Background(), settings.ingress)
	settings.reconciler.createGSLBFromIngress(settings.client, settings.ingress, strategyAnnotation, depresolver.RoundRobinStrategy)
	reconcileAndUpdateGslb(t, settings)
	require.Equal(t, len(settings.gslb.Annotations), 2)
	require.Equal(t, settings.gslb.Annotations[key], "1.1.1.2")
}

func TestChangeIngressHostName(t *testing.T) {
	const host = "found.cloud.example.com"
	settings := provideSettings(t, predefinedConfig)
	settings.ingress.Spec.Rules[0].Host = host
	_ = settings.client.Update(context.TODO(), settings.ingress)
	settings.reconciler.createGSLBFromIngress(settings.client, settings.ingress, strategyAnnotation, depresolver.RoundRobinStrategy)
	reconcileAndUpdateGslb(t, settings)
	require.Equal(t, settings.gslb.Spec.Ingress.Rules[0].Host, settings.ingress.Spec.Rules[0].Host)
	require.Equal(t, settings.gslb.Spec.Ingress.Rules[1].Host, settings.ingress.Spec.Rules[1].Host)
	require.Equal(t, settings.gslb.Spec.Ingress.Rules[2].Host, settings.ingress.Spec.Rules[2].Host)
	require.Equal(t, 3, len(settings.gslb.Spec.Ingress.Rules))
	require.Equal(t, 3, len(settings.ingress.Spec.Rules))
}
