package controllers

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"

	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"

	"github.com/golang/mock/gomock"
	"github.com/k8gb-io/k8gb/controllers/providers/assistant"
	"github.com/k8gb-io/k8gb/controllers/providers/dns"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	externaldns "sigs.k8s.io/external-dns/endpoint"
)

func TestStrategyWeight(t *testing.T) {
	// arrange
	type wrr struct {
		Region  string   `json:"region"`
		Weight  int      `json:"weight"`
		Targets []string `json:"targets"`
	}
	var tannotation = []wrr{
		{Region: "eu", Weight: 35, Targets: []string{"10.10.0.1", "10.10.0.2"}},
		{Region: "us", Weight: 50, Targets: []string{"10.0.0.1", "10.0.0.2"}},
		{Region: "za", Weight: 15, Targets: []string{"10.22.0.1", "10.22.0.2", "10.22.1.1"}},
	}

	assertAnnotation := func(gslb *k8gbv1beta1.Gslb, ep *externaldns.DNSEndpoint) error {
		annotations := &[]wrr{}
		assert.NotNil(t, ep)
		assert.NotNil(t, gslb)
		assert.Equal(t, ep.ObjectMeta.Annotations["k8gb.absa.oss/dnstype"], "local")
		var str, _ = ep.ObjectMeta.Annotations["k8gb.absa.oss/weight-round-robin"]
		err := json.Unmarshal([]byte(str), annotations)
		require.NoError(t, err)
		require.NotNil(t, annotations)
		for i, v := range *annotations {
			assert.Equal(t, tannotation[i].Weight, v.Weight)
			assert.Equal(t, tannotation[i].Region, v.Region)
			assert.ElementsMatch(t, tannotation[i].Targets, v.Targets)
		}
		return nil
	}

	targetsEU := assistant.NewTargets()
	targetsUS := assistant.NewTargets()
	targetsZA := assistant.NewTargets()
	targetsUS["us"] = assistant.Target{IPs: []string{"10.0.0.1", "10.0.0.2"}}
	targetsEU["eu"] = assistant.Target{IPs: []string{"10.10.0.1", "10.10.0.2"}}
	targetsZA["za"] = assistant.Target{IPs: []string{"10.22.0.1", "10.22.0.2", "10.22.1.1"}}
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	crSampleYaml = "../deploy/crds/k8gb.absa.oss_v1beta1_gslb_cr_weight.yaml"
	settings := provideSettings(t, predefinedConfig)
	m := dns.NewMockProvider(ctrl)
	m.EXPECT().GslbIngressExposedIPs(gomock.Any()).Return([]string{}, nil).Times(1)
	m.EXPECT().SaveDNSEndpoint(gomock.Any(), gomock.Any()).Do(assertAnnotation).Return(fmt.Errorf("save DNS error")).Times(1)
	m.EXPECT().CreateZoneDelegationForExternalDNS(gomock.Any()).Return(nil).AnyTimes()

	m.EXPECT().GetExternalTargets(gomock.Any()).Return(targetsEU).Times(1)
	m.EXPECT().GetExternalTargets(gomock.Any()).Return(targetsUS).Times(1)
	m.EXPECT().GetExternalTargets(gomock.Any()).Return(targetsZA).Times(1)
	settings.reconciler.DNSProvider = m
	settings.gslb.Spec.Strategy.Weight = make(map[string]k8gbv1beta1.Percentage, 0)
	settings.gslb.Spec.Strategy.Weight["eu"] = "15%"
	settings.gslb.Spec.Strategy.Weight["us"] = "50%"
	settings.gslb.Spec.Strategy.Weight["za"] = "25%"

	// act, assert
	_, _ = settings.reconciler.Reconcile(context.TODO(), settings.request)
}
